Update Main.py fix PYPI URL protocol
Hi, 
When i try to update a package , Stallion issue an error: 
  ProtocolError: <ProtocolError for pypi.python.org/pypi: 403 Must access using HTTPS instead of HTTP>

So line 33 should be :
PYPI_XMLRPC = 'https://pypi.python.org/pypi'